apiVersion: v1
kind: Secret
metadata:
  name: sidis-secrets
  namespace: sidis
type: Opaque
stringData:
  # Database credentials
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "UoU4CrIoGNgOtK31"
  
  # RabbitMQ credentials
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"

